### ISSUE TITLE
Got SQL error after fresh install

### ISSUE THREAD

**Issue by Wicko-Design** [RedEvo/JoomlaSitePlanner#12]
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 SQL=SELECT id, params attribs FROM zdm8j_categories WHERE id=

**Comment by Wicko-Design** [comment]
Setting     Value

PHP Built On    Linux mail.proficiencypost.com 2.6.18-274.18.1.el5 #1 SMP Thu Feb 9 12:45:44 EST 2012 x86_64
Database Version    5.5.41
Database Collation  utf8_general_ci
PHP Version     5.4.34
Web Server  Apache
WebServer to PHP Interface  cgi-fcgi
Joomla! Version     Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version    Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by cawkie** [comment]
Do you have a Category menu item with no category set?
Not sure how you would do that but it's the only way I could see this happening.

 I'm putting a 'fix' in anyway so it ignores the detail on any menu item without the article/category set.

**Comment by cawkie** [comment]
Latest commit will, hopefully, fix this.

**Comment by Wicko-Design** [comment]
Had to do complete uninstall as didn't allow new install.
Can confirm new install works ok now.
