### ISSUE TITLE
K2 User Blog

### ISSUE THREAD

**Issue by redevorob** [RedEvo/JoomlaSitePlanner#13]
Hi Pete,

Not sure if an issue or something with my local copy, thought would stick up here anyways.

Was just filling out the local site planner copy I have with menu items. Ive tried adding the "K2 - User Page (Blog)" item as a menu link. Seems to show an error at the top of the page. Everything still works ok. Just the message shows above site planner. Tried adding another user to select for the User page and still get the message.
Ill add some screengrabs to try and show...
![screen shot 2015-06-17 at 14 54 33](https://cloud.githubusercontent.com/assets/7394112/8208772/43c55360-1501-11e5-80b3-4dd7f31cc3ff.png)
![screen shot 2015-06-17 at 14 54 19](https://cloud.githubusercontent.com/assets/7394112/8208773/43c55a5e-1501-11e5-94ca-fbdc930eebf0.png)

**Comment by PhilETaylor** [comment]
looks like a comma missing between plugins and attribs? or is it an underscore?

**Comment by cawkie** [comment]
no - attribs is an alias...

**Comment by PhilETaylor** [comment]
ah ok - I would make that explicit by coding with 'as'

`select this as that from somewhere`

**Comment by cawkie** [comment]
It was attempting to process all layouts of the K2 itemlist view. Now only handling the category layout.
