### ISSUE TITLE
Error when trying to install new version

### ISSUE THREAD

**Issue by redevodm** [RedEvo/JoomlaSitePlanner#14]
When trying to install the new version over the top of a previous install get error shown in screenshot
![screen shot 2015-06-23 at 13 52 47](https://cloud.githubusercontent.com/assets/7094360/8306395/98049c62-19af-11e5-9ee9-ea651315ec28.png)

**Comment by Wicko-Design** [comment]
This issue was listed before and I thought was fixed. I had to totally uninstall and then reinstall to make work.

**Comment by cawkie** [comment]
The Component and Plugins would upgrade but the template would not.
Now fixed in both the master and NewStatuses branches.
