### ISSUE TITLE
directory error

### ISSUE THREAD

**Issue by Wicko-Design** [RedEvo/JoomlaSitePlanner#3]
JFolder: :files: Path is not a folder. Path: administrator/components/com_siteplan/images/types
Got this when i press options in site planner. 
I think you are pointing to the wrong directory as there is a directory the same path but in components and not administrator/components.

**Comment by cawkie** [comment]
Yep - I was. 
Moved various files shared by front and backend  into front end to avoid issues with protected administrator folder. 
Missed the reference in the config.xml though...
