### ISSUE TITLE
Ideas for flowchart section

### ISSUE THREAD

**Issue by Wicko-Design** [RedEvo/JoomlaSitePlanner#4]
The way I think the sitemap layout should work would be something similar to MinMaple (check out the app from the app store). But in flow chart layout instead of mind map. 
Love the way you can add new tabs by pulling off the parent and the way they all auto adjust as you add a new tab within a group. 
Colouring options are great as not only improves aesthetics but also help with organisation of groups. 
you would need to be able to show links between pages as well. 
If you were able to build this as a flow chart and then use the data to create the menu items and pages etc that would be excellent. 

On each page there should be the option so set estimated time to produce, Images, Text, people involved to create, Modules, Etc. 

Should be able to export this into a time planner to you can see how long the process takes to build. At this point you might want to be able to add costs for time and components etc. 

Just a few ideas to start with be good to see what you all think.

**Comment by RedEvo** [comment]
best to add one idea per issue :)

d

Dave Robinson CEng, CITP, MBCS
Red Evolution (Aberdeen) Ltd
Main: (+44) 01224 443551
DDI: 01224 671390
Mobile: (+44) 07710 461 776
Web - http://www.redevolution.com http://www.redevolution.com/
Profile - http://www.redevolution.com/our-people/dave-robinson/ http://www.redevolution.com/our-people/dave-robinson/
Twitter - @RedEvo
Skype - RedEvo

**Comment by Wicko-Design** [comment]
ok then lets break these up
